Homework uploading for assignment 01
usf-progdata/hw-eburkey pull request #1
Opened 2021-01-26 01:15 UTC by eburkey

@samanthashepard
@lendijoy

2021-01-26 19:08 UTC, lendijoy commented on HW01_PalmerPenguins/HW01.Rmd
> +output: html_document
Make sure to also render your output to github format. Including "keep_md: true" below the output line works.

2021-01-26 19:10 UTC, lendijoy commented on HW01_PalmerPenguins/HW01.Rmd
> +The data set of the penguins have bee organized into 344 rows and 8 columns whereas the penguins raw data has been organized into 344 rows and 17 columns. There are 165 female and 168 male penguins t
Typo: "has been"

2021-01-26 19:16 UTC, lendijoy commented on HW01_PalmerPenguins/HW01.Rmd
> +### **General Structure:**
Don't forget to include your code and output. Remember the assignment is to use at least three functions and showcase the dataset.

2021-01-26 19:18 UTC, lendijoy commented on HW01_PalmerPenguins/HW01.Rmd
> +summary(penguins)
I noticed that you also included this line above. Did you add or change something that you are showing here?

2021-01-26 19:21 UTC, lendijoy requested changes
Good start! Just a few things to add/clarify.

2021-01-27 03:34 UTC, samanthashepard commented on HW01_PalmerPenguins/HW01.Rmd
> +plot(penguins$bill_length_mm)
I'm unclear on what the x-axis is supposed to represent?

2021-01-27 03:35 UTC, samanthashepard commented on HW01_PalmerPenguins/HW01.Rmd
> +---
I ran the code and it seems to be working fine!

2021-01-27 03:37 UTC, samanthashepard commented on HW01_PalmerPenguins/HW01.Rmd
> +Bill length
I don't think it's very useful to include this, when this info is already in the table? Maybe there's a way to bold specific statistics in the output (e.g., means and medians)

2021-01-27 03:38 UTC, samanthashepard commented on HW01_PalmerPenguins/HW01.Rmd
> +### **General Structure:**
Question: what do you mean by including the output? Upload a separate file?

2021-01-27 12:05 UTC, samanthashepard commented on HW01_PalmerPenguins/HW01.Rmd
> +### **General Structure:**
Oh, output = the github document, nvm! I thought they were different things.

2021-01-28 02:23 UTC, merged